---
kind: Service
apiVersion: v1
metadata:
  name: my-imageclassificationapp
spec:
  selector:
    app: imageclassificationapp
  ports:
  - protocol: TCP
    port: 88
    targetPort: 88
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageclassificationapp
  labels:
    app: imageclassificationapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imageclassificationapp
  template:
    metadata:
      labels:
        app: imageclassificationapp
    spec:
      containers:
        - name: model-api
          image: zjbootcamp.azurecr.io/model-api
          ports:
            - containerPort: 88
      imagePullSecrets:
        - name: zjacrkey
