---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageclassificationapp
  labels:
    app: imageclassificationapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageclassificationapp
  template:
    metadata:
      labels:
        app: imageclassificationapp
    spec:
      containers:
        - name: model-api
          image: zjbootcamp.azurecr.io/model-api
          ports:
            - containerPort: 88
      imagePullSecrets:
        - name: zjacrkey
