---
apiVersion: v1
kind: Pod
metadata:
 name: imageclassificationapp
spec:
 containers:
   - name: model-api
     image: zjbootcamp.azurecr.io/model-api
     ports:
       - containerPort: 88
 imagePullSecrets:
   - name: zjacrkey
